// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEscolar.WebAPI.Data;

namespace ProjetoEscolar.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProjetoEscolar.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nilson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alexandre"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bianca"
                        });
                });

            modelBuilder.Entity("ProjetoEscolar.WebAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateBirth");

                    b.Property<string>("Lastname");

                    b.Property<string>("Name");

                    b.Property<int>("ProfessorId");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateBirth = "13/02/2000",
                            Lastname = "Lima",
                            Name = "Maria",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateBirth = "13/02/2005",
                            Lastname = "Pereira",
                            Name = "Diogo",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateBirth = "13/02/1998",
                            Lastname = "Xavier",
                            Name = "Lucas",
                            ProfessorId = 1
                        });
                });

            modelBuilder.Entity("ProjetoEscolar.WebAPI.Models.Student", b =>
                {
                    b.HasOne("ProjetoEscolar.WebAPI.Models.Professor", "Professor")
                        .WithMany("Students")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
